Algoritmo "Meu primeiro algoritimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Anderson de Oliveira Romeiro
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 
   Nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("Resultado:", nota)

Fimalgoritmo