Algoritmo "Operadores Relacionais"
// Descrição   : Operadores Relacionais
// Autor(a)    : Anderson Romeiro
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis
   nota01, nota02: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   nota01 :=10
   nota02 :=10
   
   se (nota01 <> nota02) entao
      escreval ("Nota 01 e diferente:")
   senao
      escreval ("Nota 01 e igual:")
fimse


Fimalgoritmo